### ISSUE TITLE
App crashes after taking the first 4 photos on RPi

### ISSUE THREAD

**Issue by joelpereira** [porkbuns/shmile#42]
I've loaded the latest code on my RPi 2 by following the instructions in the wiki.
The page loads but the program only takes the first 4 pictures before crashing.
I don't know where or what to fix based on the error (can't find an "events.js").

Here's my log output:
pi@raspberrypi:~/shmile $ coffee app.coffee 
(node) sys is deprecated. Use util instead.
printer is: false
   info  - socket.io started
   debug - client authorized
   info  - handshake authorized Lk2m-0dwRFhLDpSsyPVK
   debug - setting request GET /socket.io/1/websocket/Lk2m-0dwRFhLDpSsyPVK
   debug - set heartbeat interval for client Lk2m-0dwRFhLDpSsyPVK
   debug - client authorized for 
   debug - websocket writing 1::
(node) util.puts is deprecated. Use console.log instead.
Web browser connected
   debug - websocket writing 5:::{"name":"camera_begin_snap"}
   debug - websocket writing 5:::{"name":"camera_snapped"}
   debug - websocket writing 5:::{"name":"photo_saved","args":[{"filename":"05-16-19_20:51:39.jpg","path":"public/photos/05-16-19_20:51:39.jpg","web_url":"/photos/05-16-19_20:51:39.jpg"}]}
   debug - emitting heartbeat for client Lk2m-0dwRFhLDpSsyPVK
   debug - websocket writing 2::
   debug - set heartbeat timeout for client Lk2m-0dwRFhLDpSsyPVK
   debug - got heartbeat packet
   debug - cleared heartbeat timeout for client Lk2m-0dwRFhLDpSsyPVK
   debug - set heartbeat interval for client Lk2m-0dwRFhLDpSsyPVK
   debug - websocket writing 5:::{"name":"camera_begin_snap"}
   debug - websocket writing 5:::{"name":"camera_snapped"}
   debug - websocket writing 5:::{"name":"photo_saved","args":[{"filename":"05-16-19_20:51:48.jpg","path":"public/photos/05-16-19_20:51:48.jpg","web_url":"/photos/05-16-19_20:51:48.jpg"}]}
   debug - websocket writing 5:::{"name":"camera_begin_snap"}
   debug - websocket writing 5:::{"name":"camera_snapped"}
   debug - websocket writing 5:::{"name":"photo_saved","args":[{"filename":"05-16-19_20:51:57.jpg","path":"public/photos/05-16-19_20:51:57.jpg","web_url":"/photos/05-16-19_20:51:57.jpg"}]}
   debug - websocket writing 5:::{"name":"camera_begin_snap"}
   debug - emitting heartbeat for client Lk2m-0dwRFhLDpSsyPVK
   debug - websocket writing 2::
   debug - set heartbeat timeout for client Lk2m-0dwRFhLDpSsyPVK
   debug - got heartbeat packet
   debug - cleared heartbeat timeout for client Lk2m-0dwRFhLDpSsyPVK
   debug - set heartbeat interval for client Lk2m-0dwRFhLDpSsyPVK
   debug - websocket writing 5:::{"name":"camera_snapped"}
   debug - websocket writing 5:::{"name":"photo_saved","args":[{"filename":"05-16-19_20:52:06.jpg","path":"public/photos/05-16-19_20:52:06.jpg","web_url":"/photos/05-16-19_20:52:06.jpg"}]}
img_src_list is: public/photos/05-16-19_20:51:39.jpg,public/photos/05-16-19_20:51:48.jpg,public/photos/05-16-19_20:51:57.jpg,public/photos/05-16-19_20:52:06.jpg
executing: convert -size 2550x1750 canvas:white public/photos/05-16-19_20:51:39.jpg -geometry 1200x800+50+50 -composite public/photos/05-16-19_20:51:48.jpg -geometry 1200x800+1300+50 -composite public/photos/05-16-19_20:51:57.jpg -geometry 1200x800+50+900 -composite public/photos/05-16-19_20:52:06.jpg -geometry 1200x800+1300+900 -composite public/temp/out.jpg
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn convert ENOENT
  at exports._errnoException (util.js:874:11)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
  at onErrorNT (internal/child_process.js:344:16)
  at doNTCallback2 (node.js:439:9)
  at process._tickCallback (node.js:353:17)

**Comment by joelpereira** [comment]
Looks like I missed the imagemagick install line.
Running this fixed it.
`sudo apt-get install imagemagick`
